name: bullet
version: 0.9.0
dependencies:
  browser: any
  angular: 1.0.0
  web_components: any
  connector:
    git: git://github.com/maxdavidson/connector.git
  stream: any
  mongo_dart: any
  oauth2: any
  jwt: any
  quiver: any
  intl: any
dev_dependencies:
  unittest: any
transformers:
- angular:
    html_files:
    - lib/client/components/ad/ad.html
    - lib/client/components/loader/loader.html
    - lib/client/components/navbar/navbar.html
    - lib/client/views/ad/ad.html
    - lib/client/views/create-ad/create-ad.html
    - lib/client/views/login/login.html
    - lib/client/views/profile/profile.html
    - lib/client/views/search/search.html
